apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: platform

images:
  - name: order-service
    newTag: latest

  - name: auth-service
    newTag: latest

replicas:
  - name: order-service
    count: 3

  - name: auth-service
    count: 2
