apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-services
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://gitlab.com/Dhruvpatil56/cloud-native-incident-platform.git
    targetRevision: main
    path: infrastructure/kubernetes/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
