apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    name: platform
    managed-by: cloud-native-incident-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    managed-by: cloud-native-incident-platform
